FROM openjdk:8
EXPOSE 8080
COPY target/categorizePhoneNumbers-service-0.0.1-SNAPSHOT.jar categorizePhoneNumbers-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","categorizePhoneNumbers-service-0.0.1-SNAPSHOT.jar"]